### ISSUE TITLE
Doesn't work with the latest version of CoreProtect

### ISSUE THREAD

**Issue by sigma94** [SBPrime/BlocksHub#43]
The latest release of BlocksHub will not work with CoreProtect v2.14.3 (for 1.10 servers) on my 1.10 Spigot server.  Logs:

```
9:22:21 PM BlocksHub: CoreProtect: Unable to create logger.
9:22:21 PM BlocksHub: ***********************************
9:22:21 PM BlocksHub: Logger creation error
9:22:21 PM BlocksHub: ***********************************
9:22:21 PM BlocksHub: * Exception: java.lang.NoClassDefFoundError
9:22:21 PM BlocksHub: * Error message: net/coreprotect/CoreProtect
9:22:21 PM BlocksHub: * Stack:
9:22:21 PM BlocksHub: * org.primesoft.blockshub.logger.bukkit.coreProtect.BlocksHubPlugin.createLogger(BlocksHubPlugin.java:61)
9:22:21 PM BlocksHub: * org.primesoft.blockshub.api.base.BaseLoggerEndpoint.finalizeInitialization(BaseLoggerEndpoint.java:68)
9:22:21 PM BlocksHub: * org.primesoft.blockshub.api.base.BaseEndpoint.initialize(BaseEndpoint.java:98)
9:22:21 PM BlocksHub: * org.primesoft.blockshub.BlocksHubCore.loadPlugin(BlocksHubCore.java:282)
9:22:21 PM BlocksHub: * org.primesoft.blockshub.BlocksHubCore.loadPlugins(BlocksHubCore.java:228)
9:22:21 PM BlocksHub: * org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
9:22:21 PM BlocksHub: * org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
9:22:21 PM BlocksHub: * net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741)
9:22:21 PM BlocksHub: * net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
9:22:21 PM BlocksHub: * net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
9:22:21 PM BlocksHub: * net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
9:22:21 PM BlocksHub: * java.lang.Thread.run(Thread.java:748)
9:22:21 PM BlocksHub: ***********************************
9:22:21 PM BlocksHub: BlocksHub plugin CoreProtect...disabled
```

**Comment by sigma94** [comment]
Update:  I found the issue to be that I was using the wrong version of BlocksHub.
